logging.level.com.amazonaws.util.EC2MetadataUtils=error

# JPA
spring.jpa.hibernate.ddl-auto=update

# DB
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# secret ??
spring.profiles.include=secret

# DB secret
spring.datasource.url=jdbc:mariadb://${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# aws S3 -image
#cloud.aws.credentials.accessKey=${AWS_S3_ACCESSKEY}
#cloud.aws.credentials.secretKey=${AWS_S3_SECRETKEY}
#cloud.aws.s3.bucket=${BUCKET_NAME}
cloud.aws.region.static=${REGION}
cloud.aws.stack.auto=false

# Google OAuth
oauth2.google.client-id=${GOOGLE_CLIENT_ID}
oauth2.google.client-secret=${GOOGLE_CLIENT_SECRET}
oauth2.google.redirect-uri=${GOOGLE_REDIRECT_URI}
oauth2.google.token-uri=${GOOGLE_TOKEN_URI}
oauth2.google.resource-uri=${GOOGLE_RESOURCE_URI}


# Kakao OAuth
kakao.client-id=${KAKAO_CLIENT_ID}
kakao.redirect-uri=${KAKAO_REDIRECT_URI}
kakao.token-url=${KAKAO_TOKEN_URL}
kakao.profile-url=${KAKAO_PROFILE_URL}

#Naver OAuth
spring.security.oauth2.client.registration.naver.client-id=${NAVER_CLIENT_ID}
spring.security.oauth2.client.registration.naver.client-secret=${NAVER_CLIENT_SECRET}
spring.security.oauth2.client.registration.naver.redirect-uri=${NAVER_REDIRECT_URI}
spring.security.oauth2.client.provider.naver.authorization-uri=${NAVER_AUTHORIZATION_URI}
spring.security.oauth2.client.provider.naver.token-uri=${NAVER_TOKEN_URI}
spring.security.oauth2.client.provider.naver.user-info-uri=${NAVER_USER_INFO_URI}